### ISSUE TITLE
你好老哥 这个插件支持整个项目转吗

### ISSUE THREAD

**Issue by Lee981265** [liling-hash/vue-class-to-vue2#1]

**Comment by liling-hash** [comment]
哦，目前仅仅支持一个参数，可以是文件夹也可以.js或.vue


来自 MEIZU 18

-------- 原始邮件 --------
发件人：谜鹿 ***@***.***>
时间：2023年5月29日 15:24
收件人：liling-hash/vue-class-to-vue2 ***@***.***>
抄送：Subscribed ***@***.***>
主题：[liling-hash/vue-class-to-vue2] 你好老哥 这个插件支持整个项目转吗 (Issue #1)
